version: '3.9'
services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"

  build-stats-service:
    image: ghcr.io/shvatov/build-stats:main
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"

  notifications-service:
    image: ghcr.io/shvatov/build-stats-notifications:main
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_NAME=${BOT_NAME}
    depends_on:
      - postgres
      - rabbitmq

  telegram-bot-service:
    image: ghcr.io/shvatov/build-stats-ntf-telegram-bot:main
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_NAME=${BOT_NAME}
    depends_on:
      - postgres
      - rabbitmq

  ui-service:
    image: ghcr.io/shvatov/build-stats-ui:main
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - GITHUB_APP_CLIENT_ID=${GITHUB_APP_CLIENT_ID}
      - GITHUB_APP_CLIENT_SECRET=${GITHUB_APP_CLIENT_SECRET}
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8083:8083"