spring:
  main:
    allow-bean-definition-overriding: true

  mail:
    protocol: smtps
    port: 465
    host: smtp.yandex.ru
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  ntf-exchange: gh-ntf-exchange

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_NAME}

server:
  port: 8081